@baseUrl = http://localhost:3000/api/v1/causes
@causeId = {replace-with-causeId}
@jwtToken = {replace-with-jwtToken}

### Create an action for a cause
POST {{baseUrl}}/{{causeId}}/actions
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "type": "economic",
  "title": "Money for the Fire victims",
  "description": "Raising funds to provide financial help for families who lost their homes and livelihoods during the fire.",
  "target": 5000,
  "unit": "euros"
}
