@baseUrl = http://localhost:3000/api/v1/causes
@causeId = {replace-with-causeId}
@jwtToken = {replace-with-jwtToken}
@communityId = {replace-with-communityId}
@page = {replace-with-page}
@limit = {replace-with-limit}

### Get all causes
GET {{baseUrl}}
Content-Type: application/json

### Get all causes with pagination
GET {{baseUrl}}?page={{page}}&limit={{limit}}
Content-Type: application/json

### Get details of a cause
GET {{baseUrl}}/{{causeId}}
Content-Type: application/json
