@baseUrl = http://localhost:3000/api/v1
@causeId = <causeId>
@communityId = <communityId>
@page = 1
@limit = 10

### Get details of a cause
GET {{baseUrl}}/causes/{{causeId}}

### Get all causes of a community
GET {{baseUrl}}/communities/{{communityId}}/causes?page={{page}}&limit={{limit}}
