@baseUrl = http://localhost:3000/api/v1/causes
@causeId = {replace-with-causeId}
@jwtToken = {replace-with-jwtToken}

### Support a cause
POST {{baseUrl}}/{{causeId}}/supporters
Content-Type: application/json
Authorization: Bearer {{jwtToken}}
