version: '3.8'

services:
  ##
  ## Frontend
  ##
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - '3005:3005'
    networks:
      - solidarianid-network

networks:
  solidarianid-network:
    driver: bridge
    external: true
