version: "3.8"

services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - FRONTEND_HOST=frontend
      - FRONTEND_PORT=3005
      - TOKEN_SECRET=secret
      - USER_MS_LOGIN=http://api-gateway:3000/api/v1/users/auth/login
      - USER_MS_BASE_URL=http://api-gateway:3000/api/v1/users
      - COMMUNITY_MS_BASE_URL=http://api-gateway:3000/api/v1/communities
      - STATISTICS_MS_BASE_URL=http://api-gateway:3000/api/v1/statistics
    ports:
      - '3005:3005'
    networks:
      - solidarianid-network

  ##
  ## Microservices
  ##
  api-gateway:
    container_name: api-gateway
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: api-gateway
    environment:
      - NODE_ENV=production
      - API_GATEWAY_HOST=api-gateway
      - API_GATEWAY_PORT=3000
      - USERS_MS_HOST=users-ms
      - USERS_MS_PORT=3000
      - USERS_MS_URL="http://${USERS_MS_HOST}:${USERS_MS_PORT}/users"
      - COMMUNITIES_MS_HOST=communities-ms
      - COMMUNITIES_MS_PORT=3000
      - COMMUNITIES_MS_URL="http://${COMMUNITIES_MS_HOST}:${COMMUNITIES_MS_PORT}/communities"
      - CAUSES_HOST=communities-ms
      - CAUSES_PORT=3000
      - CAUSES_URL="http://${CAUSES_HOST}:${CAUSES_PORT}/causes"
      - ACTIONS_HOST=communities-ms
      - ACTIONS_PORT=3000
      - ACTIONS_URL="http://${ACTIONS_HOST}:${ACTIONS_PORT}/actions"
      - STATISTICS_MS_HOST=statistics-ms
      - STATISTICS_MS_PORT=3000
      - STATISTICS_MS_URL="http://${STATISTICS_MS_HOST}:${STATISTICS_MS_PORT}/statistics"
      - USERS_DOCS_URL="http://${USERS_MS_HOST}:${USERS_MS_PORT}/doc/users"
      - COMMUNITIES_DOCS_URL="http://${COMMUNITIES_MS_HOST}:${COMMUNITIES_MS_PORT}/doc/communities"
    ports:
      - '3000:3000'
    networks:
      - solidarianid-network

  users-ms:
    container_name: users-ms
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: users-ms
    environment:
      - NODE_ENV=production
      - USERS_MS_HOST=users-ms
      - USERS_MS_PORT=3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=solidarianid
      - JWT_SECRET=secret
      - GITHUB_CLIENT_ID=Ov23liOKlqmICEOPq6zB
      - GITHUB_CLIENT_SECRET=4d15601fa3fdc80d57cb91895fd8321bb54dd682
      - GITHUB_CALLBACK_URL=http://users-ms:3000/users/auth/github/callback
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CLIENT_ID=user-ms
      - KAFKA_GROUP_ID=user-ms-group
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    ports:
      - '3001:3000'
    networks:
      - solidarianid-network

  communities-ms:
    container_name: communities-ms
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: communities-ms
    environment:
      - NODE_ENV=production
      - COMMUNITIES_MS_HOST=communities-ms
      - COMMUNITIES_MS_PORT=3000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=solidarianid
      - MONGO_URI=mongodb://mongo:27017/solidarianid
      - JWT_SECRET=secret
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CLIENT_ID=communities-ms
      - KAFKA_GROUP_ID=communities-ms-group
      - KAFKA_TOPIC_COMMUNITIES=communities
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    ports:
      - '3002:3000'
    networks:
      - solidarianid-network

  statistics-ms:
    container_name: statistics-ms
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: statistics-ms
    environment:
      - NODE_ENV=production
      - STATISTICS_MS_HOST=statistics-ms
      - STATISTICS_MS_PORT=3000
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CLIENT_ID=statistics-ms
      - KAFKA_GROUP_ID=statistics-ms-group
      - KAFKA_TOPIC_COMMUNITIES=communities
      - KAFKAJS_NO_PARTITIONER_WARNING=1
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_CLUSTER_NAME=solidarianid
      - CASSANDRA_KEYSPACE=solidarianid
      - CASSANDRA_LOCAL_DATA_CENTER=datacenter1
      - JWT_SECRET=secret
    ports:
      - '3003:3000'
    networks:
      - solidarianid-network

networks:
  solidarianid-network:
    driver: bridge
    external: true
