version: "3.8"

services:
  ##
  ## Message Brokers
  ##
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - solidarianid-network

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - solidarianid-network

  ##
  ## Databases
  ##
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - NODE_ENV=production
      - USERS_MS_HOST=users-ms
      - USERS_MS_PORT=3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=solidarianid
      - JWT_SECRET=secret
      - GITHUB_CLIENT_ID=Ov23liOKlqmICEOPq6zB
      - GITHUB_CLIENT_SECRET=4d15601fa3fdc80d57cb91895fd8321bb54dd682
      - GITHUB_CALLBACK_URL=http://users-ms:3000/users/auth/github/callback
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CLIENT_ID=user-ms
      - KAFKA_GROUP_ID=user-ms-group
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - solidarianid-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - NODE_ENV=production
      - COMMUNITIES_MS_HOST=communities-ms
      - COMMUNITIES_MS_PORT=3000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=solidarianid
      - MONGO_URI=mongodb://mongo:27017/solidarianid
      - JWT_SECRET=secret
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CLIENT_ID=communities-ms
      - KAFKA_GROUP_ID=communities-ms-group
      - KAFKA_TOPIC_COMMUNITIES=communities
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    volumes:
      - mongo_data:/data/db
    networks:
      - solidarianid-network

  cassandra:
    image: bitnami/cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - NODE_ENV=production
      - STATISTICS_MS_HOST=statistics-ms
      - STATISTICS_MS_PORT=3000
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CLIENT_ID=statistics-ms
      - KAFKA_GROUP_ID=statistics-ms-group
      - KAFKA_TOPIC_COMMUNITIES=communities
      - KAFKAJS_NO_PARTITIONER_WARNING=1
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_CLUSTER_NAME=solidarianid
      - CASSANDRA_KEYSPACE=solidarianid
      - CASSANDRA_LOCAL_DATA_CENTER=datacenter1
      - JWT_SECRET=secret
    volumes:
      - "./apps/statistics-ms:/docker-entrypoint-initdb.d"
    networks:
      - solidarianid-network
    
volumes:
  postgres_data:
  mongo_data:
  cassandra_data:

networks:
  solidarianid-network:
    driver: bridge
    external: true
