services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - ./apps/users-ms/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    env_file:
      - ./apps/communities-ms/.env
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
