services:
  postgres:
    image: postgres:latest
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    ports:
      - '${MONGO_PORT}:27017'
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
