# Base URL
@baseUrl = http://localhost:3000/api/v1/users

### Success Case: Create a new user
POST {{baseUrl}}
Content-Type: application/json

{
  "firstName": "Joe",
  "lastName": "Doe",
  "birthDate": "1990-01-01",
  "email": "joe@example.com",
  "password": "123456Test*",
  "bio": "Hello, I'm Jane Doe!",
  "showAge": true,
  "showEmail": false
}

### Success Case: Create a new user without bio
POST {{baseUrl}}
Content-Type: application/json

{
  "firstName": "Jack",
  "lastName": "Doe",
  "birthDate": "1980-01-01",
  "email": "jack12.doe@example.com",
  "password":"123456Test*",
  "showAge": false,
  "showEmail": true
}

### Error Case: Create user with an already registered email (expected: 404 ...)
POST {{baseUrl}}
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "birthDate": "1992-01-01",
  "email": "jack12.doe@example.com",
  "password": "123456Test*",
  "bio": "Hello, I'm John Doe!",
  "showAge": true,
  "showEmail": false
}

### Error Case: Create user with a password that does not meet the requirements 
POST {{baseUrl}}
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "birthDate": "1992-01-01",
  "email": "jack.doe@example.com",
  "password": "123456Test",
  "bio": "Hello, I'm John Doe!",
  "showAge": true,
  "showEmail": false
}



