# Base URL
@baseUrl = http://localhost:3001
@jwtToken = {replace-with-token}
@userId = {replace-with-userId}
@followUserId = {replace-with-followUserId}

### Success case: follow user
POST {{baseUrl}}/users/{{followUserId}}/followers
Authorization: Bearer {{jwtToken}}

### Success case: get user followers
GET {{baseUrl}}/users/{{userId}}/followers
Authorization: Bearer {{jwtToken}}
