# Base URL
@baseUrl = http://localhost:3000/api/v1/users
@jwtToken = {replace-with-token}
@followedId = {replace-with-user-id}
@followerId = {replace-with-user-id}

### Success case: follow user
POST {{baseUrl}}/{{followedId}}/followers
Authorization: Bearer {{jwtToken}}

### Success case: get user followers with default pagination
GET {{baseUrl}}/{{followedId}}/followers
Authorization: Bearer {{jwtToken}}

### Success case: get user followers with custom pagination
GET {{baseUrl}}/{{followedId}}/followers?page=1&limit=5
Authorization: Bearer {{jwtToken}}

### Success case: get user following with default pagination
GET {{baseUrl}}/{{followerId}}/following
Authorization: Bearer {{jwtToken}}

### Success case: get user following with custom pagination
GET {{baseUrl}}/{{followerId}}/following?page=1&limit=5
Authorization: Bearer {{jwtToken}}
