@baseUrl = http://localhost:3001
@jwtToken = {replace-with-token}
@userId = {replace-with-id}

### Get user profile, requires authentication
GET {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{jwtToken}}

### Get user profile without authentication returns 401
GET {{baseUrl}}/users/{{userId}}
