@baseUrl = http://localhost:3000/api/v1/users
@jwtToken = {replace-with-jwtToken}
@userId = {replace-with-userId}

### Get user history, requires authentication
GET {{baseUrl}}/{{userId}}/history
Authorization: Bearer {{jwtToken}}
