@baseUrl = http://localhost:3000/api/v1/users

### Login success
POST  {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "jack12.doe@example.com",
  "password":"123456Test*"
}

### Login admin
POST  {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password":"123456Test*"
}

### Login failed
POST  {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "jack.doe@example.com",
  "password": "12345"
}
