@baseUrl = http://localhost:3001

### Login success
POST  {{baseUrl}}/users/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456Test*"
}

### Login failed
POST  {{baseUrl}}/users/auth/login
Content-Type: application/json

{
  "username": "jack.doe@example.com",
  "password": "12345"
}
