@baseUrl = http://localhost:3001
@jwtToken = {replace-with-token}
@userId = {replace-with-id}

### Update user request success case
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "email": "newemail@example.com",
  "bio": "Updated bio"
}

### Update user request failure case
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "email": "newemail@example.com",
  "bio": "Updated bio"
}