@baseUrl = http://localhost:3001
@jwtToken = <token>


### Get user notifications
GET {{baseUrl}}/users/:userId/notifications
Authorization: Bearer {{jwtToken}}


### Mark notification as read
PATCH {{baseUrl}}/users/:userId/notifications/:notificationId
Authorization: Bearer {{jwtToken}}
