@baseUrl = http://localhost:3000/api/v1/users
@jwtToken = {replace-with-jwtToken}
@userId = {replace-with-userId}
@notificationId = {replace-with-notificationId}

### Get user notifications
GET {{baseUrl}}/{{userId}}/notifications
Authorization: Bearer {{jwtToken}}


### Mark notification as read
PATCH {{baseUrl}}/{{userId}}/notifications/{{notificationId}}
Authorization: Bearer {{jwtToken}}
