### Global variables
@baseUrl = http://localhost:4000/push
@contentType = application/json
@userId = 'exampleUserId'
### Check if the server is running
GET {{baseUrl}}
Accept: text/plain

### Get the VAPID public key
GET {{baseUrl}}/vapidPublicKey
Accept: text/plain

### List all subscriptions
GET {{baseUrl}}/subscriptions
Accept: {{contentType}}

### Register a new subscription (example)
POST {{baseUrl}}/register
Content-Type: {{contentType}}

{
  "subscription": {
    "endpoint": "https://fcm.googleapis.com/fcm/send/example-endpoint",
    "expirationTime": null,
    "keys": {
      "p256dh": "BPxUvEVFM9ctlDqoMNuO8dCyWBOITQr5oVBWAQD5FJ-T9yLTECjBpL-u0vKdeT9khHAxWCwVcPwZFXJIAsLOJb8",
      "auth": "bZnJvGjW3Xg2i8RhvUJIqQ"
    }
  }
}

### Send a notification to a specific user
POST {{baseUrl}}/sendNotification
Content-Type: {{contentType}}

{
  "userId": {{userId}},
  "payload": "{\"title\":\"Test Notification\",\"body\":\"This is a test notification!\",\"icon\":\"/icon.png\"}",
  "ttl": 86400,
  "delay": 0
}
