# server_push/Makefile
run-prod:
	npm install
	npm run start

run-foreground-prod:
	npm run start

stop-prod:
	npm run stop

restart-prod:
	npm run restart

status-prod:
	npm run status

build-prod:
	npm install

clean-prod:
	rm -rf node_modules
