# server_push/Makefile
run-prod:
	npm install
	npm run start

run-foreground-prod:
	npm run start

stop-prod:
	npm run stop

restart-prod:
	npm run restart

status-prod:
	# Si tienes un comando para verificar el estado, puedes agregarlo aquí

build-prod:
	npm install
	# Si necesitas compilar o hacer algo más, lo añades aquí

clean-prod:
	rm -rf node_modules
