# Base URL
@baseUrl = http://localhost:3000/api/v1/communities
@jwtToken = {replace-with-jwtToken}

### Create community request
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Mi nueva comunidad",
  "description": "Una descripción breve de la comunidad",
  "cause": {
    "title": "Causa principal",
    "description": "Descripción de la causa principal",
    "end": "2025-12-31T23:59:59.000Z",
    "ods": [1, 2]
  }
}
