### Create Cause
POST http://localhost:3002/communities
Content-Type: application/json
Authorization: Bearer {token}

{
  "name": "Mi nueva comunidad",
  "description": "Una descripción breve de la comunidad",
  "cause": {
    "title": "Causa principal",
    "description": "Descripción de la causa principal",
    "end": "2025-12-31T23:59:59.000Z",
    "ods": [1, 2]
  }
}
