@baseUrl = http://localhost:3000/api/v1/communities
@jwtToken = {replace-with-jwtToken}
@communityId = {replace-with-communityId}

### Create Cause
POST {{baseUrl}}/{{communityId}}/causes
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "title": "Reforestación de bosques",
  "description": "Proyecto para plantar árboles y restaurar áreas forestales degradadas.",
  "end": "2025-12-31T23:59:59.000Z",
  "ods": [15] 
}
