
GET http://localhost:3002/communities/creation-requests
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsidmFsdWUiOiJjNzJjMGE4Yy0zYzQwLTQxNDgtYmNjZi0wZGYwOThkMDZiMDEifSwiZW1haWwiOiJqYWNrLmRvZUBleGFtcGxlLmNvbSIsInJvbGVzIjoidXNlciIsImlhdCI6MTczNTkwNzU3NSwiZXhwIjoxNzM1OTExMTc1fQ.AyJsi9STWzWJq98Gg0vgy-tTbWjuAniHqj2i6MY3Vkc
