@baseUrl = http://localhost:3000/api/v1/communities
@jwtToken = {replace-with-jwtToken}
@communityId = {replace-with-communityId}
@joinRequestId = {replace-with-joinRequestId}

### Success case: Join a community
POST {{baseUrl}}/{{communityId}}/join-requests
Authorization: Bearer {{jwtToken}}

### View all join community requests
GET {{baseUrl}}/{{communityId}}/join-requests
Authorization: Bearer {{jwtToken}}

### Validate a join community request
POST {{baseUrl}}/{{communityId}}/join-requests/{{joinRequestId}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "status": "denied",
    "comment": "Contact the community admin to join the community"
}

### Get join community request by id
GET {{baseUrl}}/{{communityId}}/join-requests/{{joinRequestId}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

