# Base URL
@baseUrl = http://localhost:3000/api/v1/communities
@jwtToken = <token>
@requestId = <requestID>

### Approve community creation request
POST {{baseUrl}}/creation-requests/{{requestId}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "status": "approved"
}

### Deny community creation request
POST {{baseUrl}}/creation-requests/{{requestId}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "status": "denied",
    "comment": "The community does not meet the minimum requirements"
}

