export enum Ods {
  NoPoverty = 'NoPoverty',
  ZeroHunger = 'ZeroHunger',
  GoodHealthAndWellBeing = 'GoodHealthAndWellBeing',
  QualityEducation = 'QualityEducation',
  GenderEquality = 'GenderEquality',
  CleanWaterAndSanitation = 'CleanWaterAndSanitation',
  AffordableAndCleanEnergy = 'AffordableAndCleanEnergy',
  DecentWorkAndEconomicGrowth = 'DecentWorkAndEconomicGrowth',
  IndustryInnovationAndInfrastructure = 'IndustryInnovationAndInfrastructure',
  ReducedInequality = 'ReducedInequality',
  SustainableCitiesAndCommunities = 'SustainableCitiesAndCommunities',
  ResponsibleConsumptionAndProduction = 'ResponsibleConsumptionAndProduction',
  ClimateAction = 'ClimateAction',
  LifeBelowWater = 'LifeBelowWater',
  LifeOnLand = 'LifeOnLand',
  PeaceJusticeAndStrongInstitutions = 'PeaceJusticeAndStrongInstitutions',
  PartnershipsForTheGoals = 'PartnershipsForTheGoals',
}
