# Base URL
@baseUrl = http://localhost:3002

### Success Case: Create a new contribution to an Action
POST  {{baseUrl}}/actions/{actionId}/contributions
Content-Type: application/json
Authorization: Bearer {jwtToken}

{
  "date": "2025-01-24",
  "amount": 50,
  "unit": "euros"
}