# Base URL
@baseUrl = http://localhost:3002

### Success Case: Create a new contribution to an Action
PATCH  {{baseUrl}}/actions/868fea09-8fe4-4e08-840f-24384382dc34/contribute
Content-Type: application/json

{
  "userId": "1",
  "date": "2025-01-24",
  "amount": 50,
  "unit": "euros"
}