# Base URL
@baseUrl = http://localhost:3002

### Success Case: Create a new economic action
POST {{baseUrl}}/causes/de1e4f77-1e10-4f1a-8353-8003256658a7/actions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsidmFsdWUiOiI0ZmM3MjZmYi0zNDBkLTRkNDUtOGVjNC0wNDlhZTgyODU4NGMifSwiZW1haWwiOiJqYWNrMTIuZG9lQGV4YW1wbGUuY29tIiwicm9sZXMiOiJhZG1pbiIsImlhdCI6MTczNjI4MTU2OCwiZXhwIjoxNzM2Mjg1MTY4fQ.qirGMo-wEVKrj7FSgdjIAJKTwn0KnMvdWleBZ2MAnzY

{
  "type": "economic",
  "title": "Money for the Fire victims-55",
  "description": "Raising funds to provide financial help for families who lost their homes and livelihoods during the fire.",
  "target": 5000,
  "unit": "euros"
}

### Success case: Create a new goods collection action
POST {{baseUrl}}/actions
Content-Type: application/json

{
  "type": "goods_collection",
  "title": "Food Aid for Communities in Somalia",
  "description": "Providing essential food supplies to families in drought-affected regions of Somalia to combat hunger and malnutrition.",
  "causeId": "cause-001",
  "target": 5000,
  "unit": "kg",
  "goodType": "Maize Meal"
}

### Success case: Create a new volunteer action
POST {{baseUrl}}/actions
Content-Type: application/json

{
  "type": "volunteer",
  "title": "Volunteer Help at Concert for Valencia Flood Relief.",
  "description": "Volunteers assist in organizing and managing a solidarity concert to raise funds for communities affected by the floods in Valencia, ensuring smooth event logistics and donations.",
  "causeId": "cause-002",
  "target": 5000,
  "unit": "hours",
  "location": "Catedral de Murcia",
  "date": "2025-01-24"
}

