# Base URL
@baseUrl = http://localhost:3002

### Success Case: Create a new economic action
POST {{baseUrl}}/actions
Content-Type: application/json

{
  "type": "economic",
  "title": "Money for the Fire victims",
  "description": "Raising funds to provide financial help for families who lost their homes and livelihoods during the fire.",
  "causeId": "cause-123",
  "targetAmount": 5000
}

### Success case: Create a new food action
POST {{baseUrl}}/actions
Content-Type: application/json

{
  "type": "food",
  "title": "Food Aid for Communities in Somalia",
  "description": "Providing essential food supplies to families in drought-affected regions of Somalia to combat hunger and malnutrition.",
  "causeId": "cause-001",
  "foodType": "Maize Meal",
  "quantity": 100,
  "unit": "kg"
}

### Success case: Create a new volunteer action
POST {{baseUrl}}/actions
Content-Type: application/json

{
  "type": "volunteer",
  "title": "Volunteer Help at Concert for Valencia Flood Relief.",
  "description": "Volunteers assist in organizing and managing a solidarity concert to raise funds for communities affected by the floods in Valencia, ensuring smooth event logistics and donations.",
  "causeId": "cause-002",
  "targetVolunteers": 30,
  "location": "Catedral de Murcia",
  "date": "2025-01-24"
}

