@baseUrl = http://localhost:3000/api/v1/actions
@causeId = {replace-with-causeId}
@actionId = {replace-with-actionId}
@page = {replace-with-page}
@limit = {replace-with-limit}

### Get all actions
GET {{baseUrl}}
content-type: application/json

### Get all actions with pagination
GET {{baseUrl}}?page={{page}}&limit={{limit}}
content-type: application/json

### Get an action by id
GET {{baseUrl}}/{{actionId}}
Content-Type: application/json

