# Base URL
@baseUrl = http://localhost:3000/api/v1/actions
@actionId = {replace-with-actionId}
@jwtToken = {replace-with-jwtToken}
### Success Case: Create a new economic action
PATCH {{baseUrl}}/{{actionId}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  // "location": "Calle Mayor, 8",
  // "targetVolunteers": 1
  // "targetAmount": 2
  // "foodType": "Chickpeas"
  "targetAmount": 10
  // "unit": "kg"
}
