# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  code-build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: ./backend/package-lock.json
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        working-directory: ./backend
        run: npm ci
      - name: Run prettier
        working-directory: ./backend
        run: npm run prettier:check
      - name: Run eslint
        working-directory: ./backend
        run: npm run lint
      - name: Build the project
        working-directory: ./backend
        run: npm run build:communities-ms
  # - name: Run tests
  #   working-directory: ./backend
  #   run: npm test
